// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Admin_Management.Models
{
    public partial class TblBlog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public string About { get; set; }
        public string BlogContent { get; set; }
        public DateTime RegDate { get; set; }
        public int? CatId { get; set; }
        public bool IsActive { get; set; }

        public virtual TblCategory Cat { get; set; }
    }
}