// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Admin_Management.Models
{
    public partial class TblCategory
    {
        public TblCategory()
        {
            TblBlog = new HashSet<TblBlog>();
        }

        public int Id { get; set; }
        public string CatName { get; set; }
        public DateTime RegDate { get; set; }

        public virtual ICollection<TblBlog> TblBlog { get; set; }
    }
}