// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Admin_Management.Models
{
    public partial class TblSubscribe
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Remote ("Is EmailAvailavle", "TblSubscribe",ErrorMessage ="Email Allready exists..")]
        public string Email { get; set; }
        public DateTime Regdate { get; set; }
        public bool Active { get; set; }
    }
}