// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Admin_Management.Models
{
    public partial class TblUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int? Mobile { get; set; }
        public bool Active { get; set; }
        public string ImagePath { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public DateTime RegDate { get; set; }
    }
}